FROM gvgramazio/sfdx

VOLUME /app
WORKDIR /app

# sfdx environment
#ENV SFDX_API_VERSION = 44.0
ENV SFDX_AUTOUPDATE_DISABLE = true
#ENV SFDX_CODE_COVERAGE_REQUIREMENT = 70
ENV SFDX_USE_GENERIC_UNIX_KEYCHAIN = true
ENV SFDX_DOMAIN_RETRY 300

# build environment
ENV CI_PROJECT_DIR /app
ENV CI_SFDX_ORG ciorg
ENV CI_SFDX_KEY assets/server.key
ENV CI_SFDX_SCRATCH_DEF config/project-scratch-def.json